#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Copyright (C) 2011-2018 OpenFOAM Foundation
#   \\  /    A nd           | Copyright (C) 2019 Yuusha
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#     This file is part of tilasoldo and Yuusha contribution to OpenFOAM.
#     It is based on chriss85 contribution for OpenFOAM 2.3.x.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# File
#     etc/bashrc
#
# Description
#     simple bashrc for tabulated properties
#
#------------------------------------------------------------------------------

# Location of tabulated properties
# You may change this value if yu want to use a different one.
export TAB_PROPERTIES=$WM_PROJECT_USER_DIR
