#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeLnInclude -u OpenFOAM
wmake $targetType thermophysicalModels/specie
wmake $targetType thermophysicalModels/basic
wmake $targetType thermophysicalModels/reactionThermo

#------------------------------------------------------------------------------
